name: Test

on: [push]

permissions:
  id-token: write
  pull-requests: write
  contents: read
  actions: read

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      TARGET_ENV_NAME: ${{ github.event.inputs.target_env_name }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Set vars
        id: set_vars
        run: |
          readonly ID="test"
          echo "ID=$ID" >> $GITHUB_OUTPUT
