name: Test

on:
  workflow_dispatch:
    inputs:
      target_env_name:
        type: choice
        description: Target env name [it0, dev, prd]
        required: true
        options: [it0, dev, prd]

permissions:
  id-token: write
  pull-requests: write
  contents: read
  actions: read

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      TARGET_ENV_NAME: ${{ steps.set_vars.outputs.TARGET_ENV_NAME }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Set vars
        id: set_vars
        run: |
          readonly ID="test"
          readonly 
          echo "ID=$ID" >> $GITHUB_OUTPUT
          echo "TARGET_ENV_NAME=$TARGET_ENV_NAME" >> $GITHUB_OUTPUT
