name: Test

on:
  workflow_dispatch:
    inputs:
      target_env_name:
        type: choice
        description: Target env name [it0, dev, prd]
        required: true
        options: [it0, dev, prd]

permissions:
  id-token: write
  pull-requests: write
  contents: read
  actions: read

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and Test with pytest
        run: |
          cd infra && \
          python -m venv .venv && \
          source .venv/bin/activate && \
          while read lambdafunction
          do
          echo "------------------------------------"
          echo "Lambda Function : $lambdafunction"
          pushd functions/$lambdafunction/
          pip install -r requirements.txt
          pip install -r test_requirements.txt
          export PYTHONPATH=$PYTHONPATH:$(pwd)/functions/my-send/main
          pytest --maxfail=1 --disable-warnings -v
          popd
          echo "------------------------------------"
          done < ./functions/pytest_functions.txt
